behaviors:
 My Behavior:
  trainer_type: ppo
  hyperparameters:
   batch_size: 1024
   beta: 1e-3
   buffer_size: 10240
   epsilon: 0.2
   lambd: 0.95
   learning_rate: 3.0e-4
   learning_rate_schedule: linear 
   num_epoch: 10  
  network_settings:
   normalize: true
   num_layers: 2
   hidden_units: 512
  reward_signals:
   extrinsic:
    strength: 1.0
    gamma: 0.99
  max_steps: 15.0e5
  time_horizon: 64
  summary_freq: 10000